window.todo = window.todo || {};

todo.actions = {

  INIT_APPLICATION: "INIT_APPLICATION",
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SELECTION_CHANGED: "SELECTION_CHANGED",
  CLEAR_COMPLETED: "CLEAR_COMPLETED"

}
